<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="TestCases/Regular/basicExataFunctionalityCheck_script" package="exatagui.suite" timestamp="2024-06-06 11:07:07.502 -0400"
 tests="2"  failures="3" errors="3" time="8.347000">
  <properties>
   <property name="RunDate" value="2024-06-06 11:07:07.502 -0400"/>
   <property name="Status" value="Failure"/>
  </properties>
  <testcase name="basicEXataFunctionalityCheck" assertions="7" status="error"  time="8.196">
    <failure type="LogError" message="Adding link to the nodes failed:ERROR: No Such Command: &apos;error&apos;" />
    <failure type="LogError" message="Error in running basicEXataFunctionalityCheck TestCase" />
    <error type="Throw" message="STUnknownMessage - ERROR: No Such Command: &apos;error&apos;" />
  </testcase>
  <testcase name="TestCases/Regular/basicExataFunctionalityCheck.script" assertions="7" status="error"  time="8.344">
    <failure type="LogError" message="Adding link to the nodes failed:ERROR: No Such Command: &apos;error&apos;" />
    <failure type="LogError" message="Error in running basicEXataFunctionalityCheck TestCase" />
    <failure type="FAILURE" message="STUnknownMessage: ERROR: No Such Command: &apos;error&apos; -- Execution Time 0:00:08 TestCases/Regular/basicExataFunctionalityCheck.script" />
    <error type="Throw" message="STUnknownMessage - ERROR: No Such Command: &apos;error&apos;" />
  </testcase>
 </testsuite>
</testsuites>
